package com.todo.exceptions;

public enum ErrorCode {
    DUPLICATE_DB_FIELD_VALUE,
    UNHANDLED_EXCEPTION,
    NO_AUTH_HEADER_FOUND,

    INVALID_AUTH_HEADER,
    INVALID_INPUT_GIVEN,

    INVALID_SERVLET_REQUEST,
    INVALID_ID_GIVEN_FOR_RESOURCE,
    UNAUTHORIZED_ACCESS,
    FIELD_ERRORS,
    ACCESS_NOT_ALLOWED,
    RESOURCE_WITH_GIVEN_ID_DOES_NOT_EXISTS,
    RESOURCE_ALREADY_EXISTS
}